Require .env for install

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -1,103 +1,44 @@
-# Details about the install.yaml file are at https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#sections-and-features-of-ddev-get-add-on-installyaml
-
 name: datadog
-
-# pre_install_actions - list of actions to run before installing the addon.
-# Examples would be removing an extraneous docker volume,
-# or doing a sanity check for requirements.
-# DDEV environment variables can be interpolated into these actions
 pre_install_actions:
-  - |
-    #ddev-description:Install agent configuration on host
-    ddev exec curl -sSL https://s3.amazonaws.com/dd-agent/scripts/install_script_docker_injection.sh -o install_script.sh
-    ddev exec DD_APPSEC_ENABLED=true DD_IAST_ENABLED=true DD_APPSEC_SCA_ENABLED=true bash install_script.sh
-    # exit 1
+  - | 
+    #ddev-description:Configure API key
+    DDEV_APPROOT=$(ddev describe -j | jq -r .raw.approot)
+    ENV_FILE="$DDEV_APPROOT/.ddev/.env"
+    DD_API_KEY=""
 
-# - |
-  # #ddev-nodisplay
-  #ddev-description:Check architecture type for incompatible arm64 type
-  # if [ "$(uname -m)" = "arm64" -o "$(uname -m)" = "aarch64" ]; then
-    # echo "This package does not work on arm64 (Apple Silicon) machines";
-    # exit 1;
-  #fi
+    # Function to read a specific variable from .env file
+    get_env_var() {
+        local var_name=$1
+        local env_file=$2
+        grep -E "^${var_name}=" "$env_file" | sed -E "s/^${var_name}=//"
+    }
 
-# - "docker volume rm ddev-${DDEV_PROJECT}_solr 2>/dev/null || true"
-#- |
-#  # Using #ddev-nodisplay tells ddev to be quiet about this action and not show it or its output.
-#  #ddev-nodisplay
-#  #ddev-description:Remove solr volume
-#  if ! ( ddev debug capabilities 2>/dev/null | grep multiple-dockerfiles >/dev/null 2>&1 ) ; then
-#    echo "This add-on requires DDEV v1.19.4 or higher, please upgrade." && exit 2
-#  fi
-#- 'echo "what is your platform.sh token" && read x'
+    # Read the DD_API_KEY from the .env file
+    if [ -f "$ENV_FILE" ]; then
+        DD_API_KEY=$(get_env_var "DD_API_KEY" "$ENV_FILE")
+    fi
 
-# This item shows templating using DDEV environment variables.
-# -
-#   #ddev-description:Touch a file to create it
-#   touch somefile.${DDEV_PROJECT_TYPE}.${DDEV_DOCROOT}.txt
-#
+    # Check if the DD_API_KEY is set and non-empty
+    if [[ -z "$DD_API_KEY" ]]; then
+        echo "Error: Missing DD_API_KEY. Add DD_API_KEY to .ddev/.env" >&2
+        exit 1
+    fi
 
-# This item shows complex go templating possibilities based on yaml_read_files
-#- |
-#- #ddev-description:Create a config.platformsh.yaml
-#  cat <<EOF >.ddev/config.platformsh.yaml
-#  php_version: {{ trimPrefix "php:" .platformapp.type }}
-#  database:
-#    type: {{ regexReplaceAll ":.*$" .services.db.type "" }}
-#    version: {{ regexReplaceAll "^.*:" .services.db.type "" }}
-#
-#  docroot: {{ dig "web" "locations" "/" "root" "notfound" .platformapp }}
-#  {{ if eq .platformapp.build.flavor "composer" }}
-#  hooks:
-#    post-start:
-#      - composer: install
-#  {{ if .platformapp.hooks.deploy }}
-#      - exec: "{{ trimAll "\n" .platformapp.hooks.deploy | splitList "\n" | join ` && ` }}"
-#  {{ end }}
-#  {{ end }}
-#
-#  EOF
+    # Validate the API key
+    if curl -sL -o /dev/null -w "%{http_code}" --location 'https://api.datadoghq.com/api/v1/validate' --header "DD-API-KEY: $DD_API_KEY" | grep -q "^200$"; then
+        echo "API Key is valid!"
+    else
+        echo "Invalid API Key!" >&2
+        exit 1
+    fi
 
-# list of files and directories listed that are copied into project .ddev directory
-# Each file should contain #ddev-generated so it can be replaced by a later `ddev get`
-# if it hasn't been modified by the user.
-# DDEV environment variables can be interpolated into these filenames
-# If you use directories, they must be directories that are managed
-# by this add-on, or removal could remove things that are not owned by it
 project_files:
   - docker-compose.datadog.yaml
-# - some-directory/file1.txt
-# - some-directory/file2.txt
-# - extra_files_dir_created_by_this_template/
-# - somefile.sh
-
-# List of files and directories that are copied into the global .ddev directory
-# DDEV environment variables can be interpolated into these filenames
-global_files:
   - commands/datadog/datadog
 
-# List of add-on names that this add-on depends on
-dependencies:
-# - redis
-
-# DDEV environment variables can be interpolated into these actions
 post_install_actions:
-  - chmod +x ~/.ddev/commands/datadog/datadog
   - |
     #ddev-description:Installing PHP agent
-    ddev exec -s datadog curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php
-    ddev exec -s datadog php datadog-setup.php --php-bin=all --enable-appsec --enable-profiling
-# - touch somefile.${GOOS}.${DDEV_WEBSERVER}
-# - perl -pi -e 's/oldstring/newstring/g' docker-compose.addon-template.yaml
-
-# Shell actions that can be done during removal of the add-on
-removal_actions:
-  - rm ~/.ddev/commands/datadog/datadog
-
-# Advanced usage - yaml files can be read in and then used as go template actions
-# in pre_install_actions and post_install_actions
-# See example in
-# https://github.com/rfay/ddev/blob/20220606_yaml_read_experiment/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml
-yaml_read_files:
-# someyaml: someyaml.yaml
-# otheryaml: someotheryaml.yaml
+    ddev exec -s web curl -sSLO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php
+    DDEV_PHP_BINARY=$(ddev exec which php)
+    ddev exec -s web sudo php datadog-setup.php --php-bin=$DDEV_PHP_BINARY --enable-appsec --enable-profiling
